fix pipeline

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,7 +1,7 @@
-variables:
-  # When Agent.JobName matches this value (and the git ref is a tag), then
-  # built artifacts will be published to Azure Blob Storage.
-  AzurePublishWhen: "Catalina-Xcode-12.4"
+# variables:
+#   # When Agent.JobName matches this value (and the git ref is a tag), then
+#   # built artifacts will be published to Azure Blob Storage.
+#   AzurePublishWhen: "Catalina-Xcode-12.4"
 
 trigger:
   tags:
@@ -39,9 +39,9 @@ jobs:
     - IS_IN_AZURE
     #vmImage: $(IMAGE_POOL)
     name: 'Test Cloud Pool'
-  timeoutInMinutes: 120
-  variables:
-  - group: XTCRunTimeArtifactsCI
+  # timeoutInMinutes: 120
+  # variables:
+  # - group: XTCRunTimeArtifactsCI
 
   steps:
 
@@ -49,73 +49,73 @@ jobs:
       echo "Hello world"
       exit 1
 
-  - script: |
-      set -e
-      sudo xcode-select --switch "/Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer"
-      echo "Xcode version: $(xcrun xcodebuild -version)"
-      echo "Xcode path: $(xcrun -f xcodebuild)"
-      echo "Xcode select path: $(xcode-select --print-path)"
-    displayName: "Select Xcode $(XCODE_VERSION)"
+  # - script: |
+  #     set -e
+  #     sudo xcode-select --switch "/Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer"
+  #     echo "Xcode version: $(xcrun xcodebuild -version)"
+  #     echo "Xcode path: $(xcrun -f xcodebuild)"
+  #     echo "Xcode select path: $(xcode-select --print-path)"
+  #   displayName: "Select Xcode $(XCODE_VERSION)"
 
-  - script: |
-      eval "$(/opt/homebrew/bin/rbenv init -)" && ruby -v
-      rbenv global 2.7.2
-      ruby -v
-      gem uninstall bundler
-      gem install bundler:2.2.7
-      bundle _2.2.7_ install
-    displayName: "Bundler 2.2.7 Install"
+  # - script: |
+  #     eval "$(/opt/homebrew/bin/rbenv init -)" && ruby -v
+  #     rbenv global 2.7.2
+  #     ruby -v
+  #     gem uninstall bundler
+  #     gem install bundler:2.2.7
+  #     bundle _2.2.7_ install
+  #   displayName: "Bundler 2.2.7 Install"
 
-  - script: |
-      set -e
-      whoami
-      echo $0
-      echo $SHELL
-      echo $PATH
-      ruby -v
-      echo -e "install: --no-document --env-shebang\nupdate:  --no-document --env-shebang" > ~/.gemrc
-      bundle install
-    displayName: "Prepare Ruby Environment"
+  # - script: |
+  #     set -e
+  #     whoami
+  #     echo $0
+  #     echo $SHELL
+  #     echo $PATH
+  #     ruby -v
+  #     echo -e "install: --no-document --env-shebang\nupdate:  --no-document --env-shebang" > ~/.gemrc
+  #     bundle install
+  #   displayName: "Prepare Ruby Environment"
 
-  - script: |
-      set -e
-      rm -rf calabash-codesign
-      [ -d "calabash-codesign" ] && rm -rf calabash-codesign
-      git clone https://$(CalabashKeychainGitHubAccessToken)@github.com/xamarinhq/calabash-codesign.git
-      calabash-codesign/apple/create-keychain.sh
-    displayName: "Download and install keychain"
+  # - script: |
+  #     set -e
+  #     rm -rf calabash-codesign
+  #     [ -d "calabash-codesign" ] && rm -rf calabash-codesign
+  #     git clone https://$(CalabashKeychainGitHubAccessToken)@github.com/xamarinhq/calabash-codesign.git
+  #     calabash-codesign/apple/create-keychain.sh
+  #   displayName: "Download and install keychain"
 
-  - script: make app-agent
-    displayName: "Make app-agent"
+  # - script: make app-agent
+  #   displayName: "Make app-agent"
 
-  - script: make ipa-agent
-    displayName: "Make ipa-agent"
+  # - script: make ipa-agent
+  #   displayName: "Make ipa-agent"
 
-  - script: make test-ipa
-    displayName: "Make test-ipa"
+  # - script: make test-ipa
+  #   displayName: "Make test-ipa"
 
-  - script: make test-app
-    displayName: "Make test-app"
+  # - script: make test-app
+  #   displayName: "Make test-app"
 
-  - script: make unit-tests
-    displayName: "Make unit-tests"
+  # - script: make unit-tests
+  #   displayName: "Make unit-tests"
 
-  - script: bundle exec bin/ci/cucumber.rb
-    displayName: "exec cucumber"
-    condition: eq(variables['IsRunCucumberTests'], 'true')
+  # - script: bundle exec bin/ci/cucumber.rb
+  #   displayName: "exec cucumber"
+  #   condition: eq(variables['IsRunCucumberTests'], 'true')
 
-  - bash: "./bin/ci/az-publish.sh"
-    env:
-      AZURE_STORAGE_ACCOUNT: $(AzureStorageAccount)
-      AZURE_STORAGE_KEY: $(AzureStorageKey)
-      AZURE_STORAGE_CONNECTION_STRING: $(AzureStorageConnectionString)
-      SOURCE_BRANCH: $(Build.SourceBranch)
-    displayName: "Publish to Azure Blob Storage"
-    condition: and(succeeded(), eq(variables['Agent.JobName'], variables['AzurePublishWhen']), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
+  # - bash: "./bin/ci/az-publish.sh"
+  #   env:
+  #     AZURE_STORAGE_ACCOUNT: $(AzureStorageAccount)
+  #     AZURE_STORAGE_KEY: $(AzureStorageKey)
+  #     AZURE_STORAGE_CONNECTION_STRING: $(AzureStorageConnectionString)
+  #     SOURCE_BRANCH: $(Build.SourceBranch)
+  #   displayName: "Publish to Azure Blob Storage"
+  #   condition: and(succeeded(), eq(variables['Agent.JobName'], variables['AzurePublishWhen']), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
 
-  - task: PublishTestResults@2
-    displayName: 'Publish Test Results'
-    inputs:
-      testResultsFiles: 'cucumber/reports/junit/*.xml'
-      failTaskOnFailedTests: true
-    condition: always()
+  # - task: PublishTestResults@2
+  #   displayName: 'Publish Test Results'
+  #   inputs:
+  #     testResultsFiles: 'cucumber/reports/junit/*.xml'
+  #     failTaskOnFailedTests: true
+  #   condition: always()
